### ISSUE TITLE
Optimize mapping file search

### ISSUE THREAD

**Issue by xtuer** [valord577/mybatis-navigator#1]
Issue:
Modules ldoa-web-boot and template-web-boot both have the same FileMapper.java and FileMapper.xml, when click the jump icon from FileMapper.java it prompts two FileMapper.xml candidates.
![](http://qtdebug.com/img/misc/mybatis-navigator-duplicate-mapper.png)

Expect:
Directly jump to the related file in the current module which the source belongs to, instead of showing all the candidates in the current project.

**Comment by valord577** [comment]
Enhanced file search in v1.2. The plug-in is adapted to `2021.1, 2021.2` and has been submitted to the market. It can be updated from the official market a few days later.
