### ISSUE TITLE
IDEA 2022.2 更新了

### ISSUE THREAD

**Issue by xtuer** [valord577/mybatis-navigator#3]
老哥你的忠实粉丝又来催更了，不支持 2022.2 了。

**Comment by valord577** [comment]
> 老哥你的忠实粉丝又来催更了，不支持 2022.2 了。

已经提交了 等待审核。 新版本可以等几天再更新 最好等个bugfix版本 比如2022.2.1

**Comment by valord577** [comment]
https://github.com/valord577/mybatis-navigator/releases/tag/2022.2-v1.2

可以从这里下载 然后本地安装

**Comment by xtuer** [comment]
> 

谢谢了。
