### ISSUE TITLE
My batis navigator is incompatible with the new version of IntelliJ IDEA 2022.2 (Ultimate Edition) Build #IU-222.3345.118

### ISSUE THREAD

**Issue by russilviu** [valord577/mybatis-navigator#4]
![image](https://user-images.githubusercontent.com/15996847/181177513-f5800faf-fc42-43df-bdd8-be078e36f611.png)
 
Please see attached the image that is describing the error for the new version of IntelliJ. Thanks in advance, and I will wait for a fix!

**Comment by valord577** [comment]
I submitted the new plugin to the marketplace a few hours ago. It is currently waiting to be reviewed. You can download from [here][1] and then install locally.

[1]: https://github.com/valord577/mybatis-navigator/releases/tag/2022.2-v1.2
